---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php supportpackage
    package:
      name:
        - "{{ apache }}"
        - "{{ php }}"
      update_cache: yes
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache php centOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
